### ISSUE TITLE
Aplicativo de treino

### ISSUE THREAD

**Issue by PhilipeeX** [PhilipeeX/4you-fit#1]
- [ ] - US: Cadastrar Usuário
- [ ] #4
- [ ] - US: Cadastrar tempo de intervalo por treino
- [ ] - US: Cadastrar carga de treino
- [ ] - US: Cadastrar tipos de treino
